[device]
name = "m7"
description = "The M7 is ZTR's answer to the M8! Smaller, faster, better in everyway :)"
digital_inputs = 3
digital_outputs = 1
analog_inputs = 1
uarts = 1


[[module]]
name = "power"
uuid = "abbbd3832ad747a0a1b0cd1b3c6d6579"

[[module]]
name = "timer"
uuid = "018e7e898ac74a06936fab03b5fc6094"

[[module]]
name = "adc"
uuid = "2e48782d9d424b678c583755877fa687"

[[module]]
name = "io"
uuid = "2fa4f8500e044f92b1368164d8e1e49c"

[[module]]
name = "kv"
uuid = "456856a298a94ef694ac809835881020"

[[module]]
name = "report"
uuid = "69fdf7ae3d5011eab77f2e728ce88125"

[[module]]
name = "register"
uuid = "a0d76aa3becf4bdabf54ebc6c6c21945"

[[module]]
name = "j1939"
uuid = "ac0e4b9c567a4f629b6f472d9ca138ce"

[[module]]
name = "ble"
uuid = "20e7068614e94d4980cbffce06f71433"

[[module]]
name = "diagnostic"
uuid = "4947e836d9414a2ab59e260b52e5e252"

[[module]]
name = "cron"
uuid = "c609d032bc7844aba78ef3044d9fbec5"

[[module]]
name = "gps"
uuid = "edce8ad7992042ecb031bff36e195163"

[[module]]
name = "action"
uuid = "9003aaa09a0c47fc8e24e738499835ef"

[[module]]
name = "command"
uuid = "fffe404e84ae497aab2625818a2fcbfa"

[[module]]
name = "equipment"
uuid = "f3e71404564c4adca6eb6d6d1db01f28"

[[module]]
name = "flags"
uuid = "87baf4f23d1b4f1fb71d1900a3177e06"

[[module]]
name = "keypad"
uuid = "11ff3fe0b38849398795d83791fdc7be"
